//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanManagement.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BONU
    {
        public int bonus_id { get; set; }
        public int bonus_gradelv_id { get; set; }
        public int bonus_percent { get; set; }
    
        public virtual GRADELEVEL GRADELEVEL { get; set; }
    }
}
