//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanManagement.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIMEOFF
    {
        public int timeoff_id { get; set; }
        public System.DateTime timeoff_date { get; set; }
        public decimal timeoff_numberOfHours { get; set; }
        public int timeoff_res_id { get; set; }
        public int timeoff_tpe_id { get; set; }
        public string timeoff_comment { get; set; }
        public int timeoff_emp_id { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual REASON_TIMEOFF REASON_TIMEOFF { get; set; }
        public virtual TYPE_TIMEOFF TYPE_TIMEOFF { get; set; }
    }
}
